# Production Docker Compose Configuration
# Usage: docker compose up
# For development: docker compose -f docker-compose.dev.yml up

services:
  # Next.js Application (Production)
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: ${PROJECT_NAME:-nextjs-app}
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Add your custom environment variables here
      # - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # - DATABASE_URL=${DATABASE_URL}
    networks:
      - nextjs-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  nextjs-network:
    driver: bridge
